version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    ignore:
      - dependency-name: 'sharp'
      - dependency-name: '@typescript-eslint/*'
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
    open-pull-requests-limit: 1
