version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      typescript-eslint:
        patterns:
          - '@typescript-eslint/parser'
          - '@typescript-eslint/eslint-plugin'
      iconify-json:
        patterns:
          - '@iconify-json/*'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
    labels:
      - 'dependencies'
    open-pull-requests-limit: 10
    reviewers:
      - 'mingjunlu'
